#!/bin/sh
python3 DRILL_RAKI/flask_end_point.py \
--path_knowledge_base "$KG" \
--path_knowledge_base_embeddings "$EMBEDDINGS" \
--pretrained_drill_avg_path "$PRE_TRAINED_AGENT" \
--max_test_time_per_concept '$TIMEOUT'
